spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://ubuntu:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ming
    max-idle: 20
  redis:
    database: 0
    host: ubuntu
    port: 6379
zhongkouwei:
  timeOut: 7